name: 'Setup Koka'
description: 'Setup Koka Environment (on Linux, macOS for now)'
inputs:
  packages:  # id of input
    description: 'Packages to install, space-separated list of package names'
    required: false
    default: "std"
    type: string
  koka_repository:
    description: 'Koka repository (defaults to koka-lang/koka)'
    required: false
    default: "koka-lang/koka"
    type: string
  koka_version:
    description: 'Koka version (ignored if koka_ref is set)'
    required: false
    default: "3.2.2"
    type: string
  koka_ref:
    description: 'Koka ref (development version)'
    required: false
    default: ""
    type: string
  run_tests:
    description: 'Run tests after setup'
    required: false
    default: 'false'
    type: boolean

runs:
  using: "composite"
  steps:

    # ======================
    # Release steps
    # ======================
    - name: Setup Koka (release)
      if: inputs.koka_ref == ''
      run: |
        curl -sSL "https://github.com/koka-lang/koka/releases/download/v${{ inputs.koka_version }}/install.sh" | sh -s -- --prefix=~/.kokac --force
      shell: bash

    # ======================
    # Development steps
    # ======================
    - name: Checkout Koka
      if: inputs.koka_ref != ''
      id: checkout-koka
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.koka_repository }}
        ref: ${{ inputs.koka_ref }}
        path: tmp-koka
        submodules: recursive
    - name: Restore cache
      if: inputs.koka_ref != ''
      id: cache-koka-restore
      uses: actions/cache/restore@v5
      with:
        path: ~/.kokac
        key: koka-${{ steps.checkout-koka.outputs.commit }}-bin
    - uses: freckle/stack-action@v5
      if: inputs.koka_ref != '' && steps.cache-koka-restore.outputs.cache-hit != 'true'
      with:
        test: false
        working-directory: tmp-koka
        stack-build-arguments: --fast
    - name: Install Koka
      if: inputs.koka_ref != '' && steps.cache-koka-restore.outputs.cache-hit != 'true'
      working-directory: tmp-koka
      run: |
        stack run -- -e util/bundle -- --install --prefix=$HOME/.kokac
      shell: bash
    - name: Remove temporary checkout
      if: inputs.koka_ref != ''
      shell: bash
      run: |
        rm -rf tmp-koka
    - name: Save cache
      if: inputs.koka_ref != '' && steps.cache-koka-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ~/.kokac
        key: ${{ steps.cache-koka-restore.outputs.cache-primary-key }}


    # ======================
    # Common setup steps
    # ======================
    # TODO: Setup vcpkg
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install Koka Packages
      run: |
        install.sh ${{ inputs.packages }}
        echo "$HOME/local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Run Koka Tests
      if: inputs.run_tests == 'true'
      shell: bash
      run: |
        echo "Running Koka tests..."
        koka -e std/test/detect

