name: self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        koka_ref: ['dev', '']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Koka
        uses: './'
        with:
          self_repository: ${{ github.repository }}
          self_ref: ${{ github.ref }}

          koka_version: '3.2.3'
          koka_ref: ${{ matrix.koka_ref }}
          packages: 'std'


      - run: koka --version
        shell: bash
